### ISSUE TITLE
Downloaded files have root:root file ownership

### ISSUE THREAD

**Issue by d2s** [taskinen/yle-dl-docker#4] opened 2017-12-22 15:18 UTC
## Problem

When running the container on a Linux desktop, container output files have wrong file ownership details:

Command to run:
```
docker run --rm -ti -v `pwd`:/out taskinen/yle-dl https://areena.yle.fi/1-4305025
```

Terminal output of the command:
```
yle-dl 2.30: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2017 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3
Output file: Kioski trending: Tiede(pila)puhelu: Gravitaatioaaltojen selittäminen tuntemattomalle-2017-12-12T15:45.flv

                            KSV Adobe HDS Downloader

Processing manifest info....                                                   
Quality Selection:                                                             
 Available: 2650 1057 742 438 202
 Selected : 2650                                                               
Fragments Total: 37, First: 1, Start: 1, Parallel: 8                           
Downloading 37/37 fragments                                                    
Found 37 fragments                                                             
Finished                                                                       
Stream saved to Kioski trending: Tiede(pila)puhelu: Gravitaatioaaltojen selittäminen tuntemattomalle-2017-12-12T15:45.flv
```

The file permissions of output files (when looked with `ls -la`).
```
-rw-r--r--  1 root root 74099099 joulu 22 17:01 Kioski trending: Tiede(pila)puhelu: Gravitaatioaaltojen selittäminen tuntemattomalle-2017-12-12T15:45.flv
```

That can be fixed manually (on the host system) with:
```
sudo chown USERNAME.GROUP *.flv
```
Replace `USERNAME.GROUP`with your account's User ID (uid) and Group ID (gid).

## Potential solution

One potential option for solution might be to create a new user account to the container, and run the `yle-dl` command with that account's permissions.

There are some other options that might _not_ work, since the container needs to interact with the input parameters. Another option might be to create a wrapper script that takes the current uid.gid of the user running the container in the host system, passes those as the command line parameters to the Docker run command. It would pass those to a wrapper script inside of the container (that would then create new user account inside of the Alpine Linux, with a uid and gid numbers that match those of the host system).

It is possible to set the user & group id that would be used inside the container, but this command will fail since there are no such uid & gid items in the passwd inside of the container.
```sh
docker run --rm -ti -u=`1000:1000` -v `pwd`:/out taskinen/yle-dl YLE_URL_TO_DOWNLOAD
```

### File permissions 

- "Use `install` i.e RUN install -m 644 -o owner -g group filename"
  - https://twitter.com/alfiedotwtf/status/942867435329171456
- "Or if you have a large list, build the list inside the container, then `RUN cat file name | 
xargs chown ...`"
  - https://twitter.com/alfiedotwtf/status/942867698316275714

**Comment by taskinen** [comment] 2018-04-17 13:54
Hi and sorry for the late reply!

For me (Ubuntu 18.04 and Docker 17.03.2-ce) the `-u` parameter for `docker run` command works as intended. For my knowledge, the user or group does not need to exist inside the container. Docker runs the process with the given uid and gid (numerical) and thus the files created are also owned by them.

```
$ docker run --rm -ti -u=`id -u`:`id -g` -v `pwd`:/out taskinen/yle-dl https://areena.yle.fi/1-4305025
$ ls -la
-rw-r--r--  1 timo timo 74099099 Apr 17 16:51 'Kioski trending: Tiede(pila)puhelu: Gravitaatioaaltojen selittäminen tuntemattomalle-2017-12-12T15:45.flv'
```
If you can confirm this, I will update the example command to include the (very helpfull) `-u` parameter.

**Comment by 2-4601** [comment] 2018-05-05 00:22
I'm hazarding a guess that @d2s run in to the error because of a small typo:
> It is possible to set the user & group id that would be used inside the container, but this command will fail since there are no such uid & gid items in the passwd inside of the container.
>```
>docker run --rm -ti -u=`1000:1000` -v `pwd`:/out taskinen/yle-dl YLE_URL_TO_DOWNLOAD
>```

There seem to be backticks around the 1000:1000 part which will surely make the command fail.

---

I can confirm that the `--user` option for `docker run` works as intended.

**Comment by taskinen** [comment] 2018-05-17 15:29
Seems reasonable. I will close this issue now. I will make sure the `-u` parameter is documented.

**Closed as completed by taskinen** 2018-05-17 15:29 UTC
